"""Pure domain models — no I/O, no driver types (DESIGN §4)."""

from .catalog import (
    CheckConstraint,
    Column,
    Database,
    ForeignKey,
    IncomingForeignKey,
    PrimaryKey,
    ReferentialAction,
    Table,
    TableKind,
    TableMetadata,
    TableSummary,
    Trigger,
    UniqueConstraint,
)
from .changes import (
    ChangeKind,
    ChangeSet,
    PendingChange,
    describe_changes,
    is_new_row,
    new_row_key,
    row_label,
)
from .connection import (
    AuthMode,
    ConnectionOptions,
    ConnectionProfile,
    ConnectionResult,
    Environment,
)
from .identifiers import TableRef, validate_identifier
from .rows import (
    FetchSpec,
    FilterOp,
    Row,
    RowFilter,
    RowKey,
    RowPage,
    SortKey,
    make_row_key,
)

__all__ = [
    "AuthMode",
    "ChangeKind",
    "ChangeSet",
    "CheckConstraint",
    "Column",
    "ConnectionOptions",
    "ConnectionProfile",
    "ConnectionResult",
    "Database",
    "Environment",
    "FetchSpec",
    "FilterOp",
    "ForeignKey",
    "IncomingForeignKey",
    "PendingChange",
    "PrimaryKey",
    "ReferentialAction",
    "Row",
    "RowFilter",
    "RowKey",
    "RowPage",
    "SortKey",
    "Table",
    "TableKind",
    "TableMetadata",
    "TableRef",
    "TableSummary",
    "Trigger",
    "UniqueConstraint",
    "describe_changes",
    "is_new_row",
    "make_row_key",
    "new_row_key",
    "row_label",
    "validate_identifier",
]
